configs:
  pgadmin-servers:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "Local Postgres",
            "Group": "Servers",
            "Host": "pgDatabase",
            "Port": 5432,
            "MaintenanceDB": "postgres",
            "Username": "streamingServiceAccount",
            "PassFile": "/config/pgpass"
          }
        }
      }
  pgadmin-pgpass:
    content: |
      pgDatabase:5432:*:streamingServiceAccount:tempPassword

services:
  pgDatabase:
    image: postgres
    restart: always
    shm_size: 120mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: tempPassword
      POSTGRES_USER: streamingServiceAccount
      POSTGRES_DB: streaming-db
  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    depends_on:
      - pgDatabase
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    configs:
      - source: pgadmin-pgpass
        target: /config/pgpass
        uid: "5050"
        gid: "5050"
        mode: 0400
      - source: pgadmin-servers
        target: /pgadmin4/servers.json
        mode: 0444
